# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-18 09:56
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_image_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=imagekit.models.fields.ProcessedImageField(upload_to=''),
        ),
    ]
